package fr.agriotes.planning.models;

public enum Color {
    AQUA, CORAL, OLIVEDRAB, GOLD, LIGHTBLUE, FIREBRICK, MEDIUMAQUAMARINE, GOLDENROD, STEELBLUE, PLUM, LIGHTGREEN, KHAKI, SLATEBLUE, LIGHTSALMON, DARKSEAGREEN, ORANGE, MEDIUMPURPLE, TOMATO, YELLOWGREEN, DARKKHAKI, CORNFLOWERBLUE, INDIANRED, TEAL, MOCASSIN
}
